version: '3.8'

services:
  landcover-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landcover-flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./credentials:/app/credentials
      - ./logs:/app/logs
      - ./app/static/maps:/app/app/static/maps
    environment:
      - FLASK_APP=run.py
      - FLASK_CONFIG=production
      - PYTHONUNBUFFERED=1
      - GUNICORN_WORKERS=4
      - GUNICORN_TIMEOUT=120
    networks:
      - landcover-network

networks:
  landcover-network:
    driver: bridge
